### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by haslingera** [sarahschuetz/Blockhalde#2]
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: no uniform with name 'u_view' in shader
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:287)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:277)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:507)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:498)
	at com.blockhalde.Blockhalde.render(Blockhalde.java:76)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by tapirbug** [comment]
Bei mir gabs auch GLSL-Kompatibilititätsprobleme:

1. blocks.fs.glsl: `v_normal = normalize(v_normal);`: Schreibzugriff auf varyings nicht erlaubt, gefixt
2. blocks.fs.glsl: `v_eyeVec = normalize(v_eyeVec);` Same
3. blocks.fs.glsl: `pow( max( dot(reflectVec, eyeVec), 0.0), 2);`: Exponent muss gleichen Typ haben, also 2.0, gefixt
