### ISSUE TITLE
can't run desktop/blockhalde

### ISSUE THREAD

**Issue by jul-ya** [sarahschuetz/Blockhalde#4]
I can't run our project anymore, seems like somethings wrong with the classpath but it can't be :s
Using Eclipse Neon. Haven't found a solution and done a lot of googling on that problem, nothing worked so far.

That's the stack trace:

Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/ashley/core/EntitySystem
	at com.blockhalde.desktop.DesktopLauncher.main(DesktopLauncher.java:15)
Caused by: java.lang.ClassNotFoundException: com.badlogic.ashley.core.EntitySystem
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

Any ideas?

**Comment by urstruktur** [comment]
Had the same problem. Updated eclipse and extensions, restarted and it worked again.

**Comment by jul-ya** [comment]
Didn't work out for me, unfortunately. Maybe we can talk about that on Monday and resolve it then.

**Comment by jul-ya** [comment]
Got really mad and finally switched to IntelliJ - wanted to do that anyways. Everything works fine here, so I'll close the issue - but it would still be nice to know what exactly is the problem with Eclipse..

**Comment by tapirbug** [comment]
I also had a hard time using Eclipse at first with similar errors. I set up the project differently then, and it seems to work. I can show you on monday if you want (:
